# Site settings
name: Ben Parks
title: Chief Executive Officer
email: ceo@benparks.net
description: "violist and programmer"
baseurl: ""
url: "http://benparks.net"
github: "bnprks"

# Build settings
markdown: kramdown
permalinks: pretty
